"""Offline evaluator: compare Baseline vs Personalized ranking on historical logs.

Metrics:
- MRR (Mean Reciprocal Rank) of the clicked article.
"""
import json
import numpy as np
from pathlib import Path
import sys
import os

# Add project root to sys.path to allow running script directly
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.personalizer import load_article_topics, build_user_topic_profiles, rerank_with_user_profile
from collections import defaultdict

def load_logs(path):
    sessions = []
    with open(path, "r", encoding="utf8") as f:
        for line in f:
            sessions.append(json.loads(line))
    return sessions

def evaluate(sessions, article_topics, train_ratio=0.8):
    # Split
    n = len(sessions)
    cut = int(n * train_ratio)
    train_sessions = sessions[:cut]
    test_sessions = sessions[cut:]
    
    print(f"Total sessions: {n}, Train: {len(train_sessions)}, Test: {len(test_sessions)}")
    
    # Train profiles on Train set
    # We need to dump train sessions to a temp file to use existing build_user_topic_profiles
    # or just refactor. Let's just implement a quick builder here or use the existing one if we save to file.
    # For speed, let's just manually build here.
    user_profiles = {}
    # ... (logic similar to build_user_topic_profiles but in-memory list) ...
    # Actually, let's reuse the logic by writing a temp file, it's cleaner.
    
    temp_train_log = "logs/temp_train.jsonl"
    with open(temp_train_log, "w", encoding="utf8") as f:
        for s in train_sessions:
            f.write(json.dumps(s) + "\n")
            
    user_profiles = build_user_topic_profiles(temp_train_log, article_topics)
    
    # Evaluate on Test set
    mrr_baseline = []
    mrr_personalized = []
    
    for s in test_sessions:
        user_id = s["user_id"]
        ranked_ids = s["ranked_article_ids"] # The list shown to user (Baseline usually)
        actions = s["actions"]
        
        # Identify clicked articles
        clicked_indices = []
        for i, acts in enumerate(actions):
            if acts and any(a == "Click" for a in acts):
                clicked_indices.append(i)
                
        if not clicked_indices:
            continue
            
        # We assume the `ranked_ids` in the log were generated by the BASELINE (TF-IDF).
        # So the baseline rank of the clicked article is just its index + 1.
        # (Note: If the logs were generated by a personalized run, this assumption fails. 
        # But we assume we are evaluating on baseline logs).
        
        # For simplicity, take the FIRST clicked article
        target_idx = clicked_indices[0]
        target_id = ranked_ids[target_idx]
        
        # Baseline MRR
        mrr_baseline.append(1.0 / (target_idx + 1))
        
        # Personalized Reranking
        # We take the SAME candidates (ranked_ids) and re-rank them using the profile.
        if user_id in user_profiles:
            # Create dummy scores for input to rerank (since we don't have original TF-IDF scores easily available)
            # We can assume the input order implies score, e.g., 10, 9, 8...
            # or just pass 0.0 if we only care about topic boost.
            # Let's pass a fake score that preserves order: 1.0 down to 0.1
            candidates = [(aid, 1.0 - (i * 0.01)) for i, aid in enumerate(ranked_ids)]
            
            reranked = rerank_with_user_profile(candidates, article_topics, user_profiles[user_id], alpha=0.5)
            reranked_ids = [x[0] for x in reranked]
            
            # Find where the target_id ended up
            try:
                new_rank = reranked_ids.index(target_id)
                mrr_personalized.append(1.0 / (new_rank + 1))
            except ValueError:
                mrr_personalized.append(0.0)
        else:
            # No profile -> same as baseline
            mrr_personalized.append(1.0 / (target_idx + 1))
            
    print(f"Mean Reciprocal Rank (MRR):")
    print(f"  Baseline:     {np.mean(mrr_baseline):.4f}")
    print(f"  Personalized: {np.mean(mrr_personalized):.4f}")
    
    improvement = (np.mean(mrr_personalized) - np.mean(mrr_baseline)) / np.mean(mrr_baseline) * 100
    print(f"  Improvement:  {improvement:+.2f}%")

if __name__ == "__main__":
    article_topics = load_article_topics("articles.jsonl")
    logs = load_logs("logs/sessions.jsonl")
    if not logs:
        print("No logs found. Run sessions first.")
    else:
        evaluate(logs, article_topics)
